### ISSUE TITLE
multiple error

### ISSUE THREAD

**Issue by egyshell** [dwisiswant0/gD0rk#1]
PHP Warning:  include(vendor/mwhite/random-uagent/uagent.php): failed to open stream: No such file or directory in /home/arch/gD0rk/gd0rk.class.php on line 15
PHP Warning:  include(): Failed opening 'vendor/mwhite/random-uagent/uagent.php' for inclusion (include_path='.:') in /home/arch/gD0rk/gd0rk.class.php on line 15

  D0rk: inurl:index.php?id= ext:php

PHP Fatal error:  Uncaught Error: Call to undefined function dwisiswant0\gD0rk\random_uagent() in /home/arch/gD0rk/gd0rk.class.php:38
Stack trace:
#0 /home/arch/gD0rk/gd0rk.class.php(49): dwisiswant0\gD0rk\main->hajar('https://www.goo...', NULL, Array, NULL, 0)
#1 /home/arch/gD0rk/gd0rk.php(26): dwisiswant0\gD0rk\main->gD0rk('inurl:index.php...', NULL, NULL, 0)
#2 {main}
  thrown in /home/arch/gD0rk/gd0rk.class.php on line 38

**Comment by egyshell** [comment]
solved 
composer require mwhite/random-uagent
