### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by ohmydog31** [dwisiswant0/gD0rk#3]
D0rk: inurl:index.php?id= ext:php

PHP Fatal error:  Uncaught Error: Call to undefined function dwisiswant0\gD0rk\curl_init() in /root/gD0rk/gd0rk.class.php:19
Stack trace:
#0 /root/gD0rk/gd0rk.class.php(49): dwisiswant0\gD0rk\main->hajar('https://www.goo...', NULL, Array, NULL, 0)
#1 /root/gD0rk/gd0rk.php(26): dwisiswant0\gD0rk\main->gD0rk('inurl:index.php...', NULL, NULL, 0)
#2 {main}
  thrown in /root/gD0rk/gd0rk.class.php on line 19

------------------------
any solution?

**Comment by scumdestroy** [comment]
got the same
